"""Add webhook_url

Revision ID: e9653d1d9283
Revises: 6fd3c4e2d19c
Create Date: 2025-12-23 03:04:01.113139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9653d1d9283'
down_revision: Union[str, None] = '6fd3c4e2d19c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_versions', sa.Column('webhook_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_versions', 'webhook_url')
    # ### end Alembic commands ###
